name: beer_funk_github
description: 

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_tts_improved: ^1.0.3
  liquid_progress_indicator: ^0.3.2
  flutter_svg: ^0.17.3+1
  provider: ^4.0.4
  simple_animations: ^1.3.11
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
    - family: Barlow
      fonts:
        - asset: assets/fonts/BarlowSemiCondensed-Bold.ttf
          weight: 600
        - asset: assets/fonts/BarlowSemiCondensed-Regular.ttf
          weight: 400

  assets:
    - assets/img/bacterial.png
    - assets/img/brush.png
    - assets/img/vinegar-bottle.png
    - assets/img/detergent.png
    - assets/img/almond.png